language: android
android:
  components:
  # The SDK version used to compile your project
  - android-17
  # Additional components
  - extra-android-m2repository
android:
  licenses:
  - android-sdk-license-.+

before_install: cd source
